# Generated by Django 5.0.1 on 2024-04-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='movielog',
            name='date_watched',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='movielog',
            name='user_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
