# Generated by Django 5.0.1 on 2024-04-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_year_alter_movielog_date_watched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='user_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
